### ISSUE TITLE
💡 [Feature]: Adds additional capabilities to sample view

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#155]
## 🎯 Aim of the feature

The aim of this issue is to develop additional features for the sample gallery:
- [ ] 1. add selected filters and clear filters button  - maybe similar to TT add tags that represent each filter set with a button to clear all picked filters

![image](https://github.com/pnp/vscode-viva/assets/58668583/55cb5e33-3841-4670-9e63-8630ac84b320)

- [ ] 2. when navigating back from the detail view it does not save the state of the filters. This is a bit annoying as everytime we need to start from scratch and set the filters back. 
- [ ] 3. small annoying detail - in samples gallery when opening the details view when scroll in the previous view was not a the top then the scroll in details view is also lower. We should set it top

**Comment by Adam-it** [comment]
when scroll is not at the top when entering detail view then it is also somewhere in the middle of the page instead at the top

**Comment by DevPio** [comment]
working on this task

**Comment by Adam-it** [comment]
> working on this task

Awesome 👍. You Rock 🤩. I assigned you to the issue.
In future please first let us know to get assigned to the issue and then start coding so that we may avoid situations that more people are working on same issue 😅.

If there will be anything blocking you please do let me know 👍

**Comment by Adam-it** [comment]
PR merged. I will release a new pre-release with this truly awesome contribution in a bit. 
After some time it will get merged to `main` branch and become part of next minor release  👍💪
After this will get merged to `main` you will also be part of contributors to this repo 👏👏👏

**Comment by Adam-it** [comment]
Pre-release will be out shortly 👏
This will be part of next minor release 👍
Thank you once again for your awesome contribution 😍
You Rock 🤩
