### ISSUE TITLE
💡 [Feature]: The `Upgrade` and `Validate` actions could return also code tour response

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#188]
## 🎯 Aim of the feature

As internally those actions use the `project upgrade` and `project doctor` CLI for M365 commands and those support also the `tour` output mode which create a code tour for the current project with the findings. We could extend those functionalities so that we return the markdown sum up report and the tour in one go.

## Proposed implementation

In the `CliActions` service we the upgrade and validate methods. Each of those just run the CLI command under the hood with `md` output mode.
![image](https://github.com/pnp/vscode-viva/assets/58668583/5fdb9dfe-5cb9-4756-8c4c-1fa6241fbe4c)

Depending on the what user have saved in the setting (see below) we should execute either the command with `md` or `tour` output or execute the commands twice with both output for both

## Additional Proposal

Similar to node settings we could add additional setting for those features. For each of those features: `upgrade` and `validate` we could provide a dropdown with options that define what report type should be generated. Either: `markdown` (as we have now), `code tour`, `both` (which should be the default value)
![image](https://github.com/pnp/vscode-viva/assets/58668583/c8334097-e617-4ff3-a931-a29c36e35fe0)

**Comment by nicodecleyre** [comment]
Hi there  👋 , can i work on this one please?

**Comment by Adam-it** [comment]
> Hi there  👋 , can i work on this one please?

Of course

**Comment by Adam-it** [comment]
Hi @nicodecleyre,
Hows the work coming up with this issue?
Do you need any additional help from my side? 
This year the SPFx Toolkit repo will participate in hacktoberfest and this issue will count so if you are also planning to join this event please do remember to rise a PR during October (no sooner no later 😉) 
Once again thanks for taking extra interest in this product. You Rock 🤩

**Comment by Adam-it** [comment]
PR merged. This will be live as a new pre-release soon. 
Thank you once again for helping out in making the best SPFx tooling in the world 🚀
