### ISSUE TITLE
💡 [Feature]: Add more settings for the extension

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#200]
### 🎯 Aim of the feature

We should extend the extension settings to allow to:

- [ ] show hide service incident list
- [ ] show hide tenant wide extensions

![image](https://github.com/pnp/vscode-viva/assets/58668583/a31531e3-70a5-4ebc-b7a2-7b52977f86fa)

### 👣 How to start guide

extension settings are defined in the package.json. We should extend it with two new settings 
![image](https://github.com/pnp/vscode-viva/assets/58668583/9d9142e0-7f63-446f-9846-4b3fe0110068)

we should move the getExtensionSettings to a separate util file and refactor the `TerminalCommandExecuter` to use this util
![image](https://github.com/pnp/vscode-viva/assets/58668583/3b9323ee-886c-437a-951e-be24352a200e)

then in the `CommandPanel` we should modify the `accountTreeView` and `appcatalogTreeView` to execute the `CliActions` only if the setting is set to make those information visible
![image](https://github.com/pnp/vscode-viva/assets/58668583/19d613d4-027b-492e-b695-ef72b0448d93)

**Comment by GuidoZam** [comment]
Working on it! 😸

**Comment by Adam-it** [comment]
The related PR was merged 😍. 
Soon we will release a new pre-release with this change. 
After some time this will get merged to `main` branch and be part of a regular minor release. 
After this will get merged to `main` branch you will also be mentioned in the repo contributors. 
Thanks a ton 👏👏. You Rock 🤩
