### ISSUE TITLE
💡 [Feature]: refactor the action naming

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#209]
## 🎯 Aim of the feature

Align the actions naming to use `project` instead of `current project`

## 📷 Images (if possible) with expected result

![image](https://github.com/pnp/vscode-viva/assets/58668583/49e829f0-f9ec-4b62-8d4b-343d01bb95d8)

**Comment by nicodecleyre** [comment]
Can I work on this one? ✋

**Comment by Adam-it** [comment]
sure. 
Thank you for taking it on 👍
I am still working on a better contribution guide and more clarity in current issues and more `good first issues`, so if there is anything that you find blocking you from work just reach me out directly for help

**Comment by Adam-it** [comment]
@nicodecleyre just to let you know I updated the [contributing guidance](https://github.com/pnp/vscode-viva/blob/main/contributing.md). Maybe it might be helpful in your development

**Comment by Adam-it** [comment]
Merged ✅
your change was released as a new pre-release v3.0.2 (pre-release are not installed automatically and you need to opt-in first time to get it)
![image](https://github.com/pnp/vscode-viva/assets/58668583/d368bbdf-75c7-4968-ad53-11e17953fbe0)

at the end of this week I will be doing a new minor release of this extension and this change will be part of it.

Thank you for helping out in making the best SPFx tooling in the world 👏👏👏 You Rock 🤩
