### ISSUE TITLE
🐞 [Bug]: Serve fails if folder path has space

### ISSUE THREAD

**Issue by Tanddant** [pnp/vscode-viva#212]
## 📝 Describe the bug

When I press the serve button and the path to the folder has a space in it PowerShell `cd` fails

i.e if my project is stored at:

`d:\Client name with spaces\Project 1`

I'll get the following output:

``` PowerShell
cd d:\Client name with spaces\Project 1
> Set-Location: A positional parameter cannot be found that accepts argument 'name'.
```

## 👣 Steps To Reproduce

1. Open a project that's stored in a path with a space in it
2. Press the serve button

## 📜 Expected behavior

Serve my project.

## 💻 Desktop (please complete the following information):

 - OS: Windows 11
 - Browser N/A
 - Version 3.0.0

## 🤔 Additional context

Seems like all that's needed is to wrap the paramater containing the path in a set of quotes, I would love to help, but I have idea where to look in the code, so if anyone can point me in a direction I would love to help fix it

**Comment by Adam-it** [comment]
hi @Tanddant 👋
Sorry to hear you are having trouble using SPFx Toolkit 😔 and thank you so so much for reporting the bug 🐞.
From what you descried I also (as you suggested) think that the path should be just wrapped in single quotes 👍. 
Seems I totally forgot one may use `space` in folder names 😅.

... anyway. like 90% this is the place which should be fixed
https://github.com/pnp/vscode-viva/blob/c11c78f5ebbbd4965c3943b6287a15cc6f7958ca/src/services/TerminalCommandExecuter.ts#L120

The `TerminalCommandExecuter.runCommand` method executes every of the gulp task commands. At the beginning it sets the user newly created terminal in right position which needs to be fixed.

Would you like to give it a try?
I am still working on better contributing guidance on this repo as it is a bit problematic but you may always follow along with the current [Contribution guidelines](https://github.com/pnp/vscode-viva/blob/main/contributing.md) and if anything seems wrong or stopping you from work just let me know either here or directly 👍

**Comment by Tanddant** [comment]
For sure I'll give it a go! - never worked on a VS Code extension before, new stuff is always fun, feel free to assign me this task 😊

**Comment by Adam-it** [comment]
> For sure I'll give it a go! - never worked on a VS Code extension before, new stuff is always fun, feel free to assign me this task 😊

Sold 🔨
VS Code extensions it's a world of its own 😅. Just like SPFx 😜 
Let me know if you will need any help.

**Comment by Adam-it** [comment]
shipped with -> https://github.com/pnp/vscode-viva/actions/runs/8698251355

**Comment by Adam-it** [comment]
hi @Tanddant, 
Once again thank you for rising up the issue 👏 and solving it 🚀. You Rock 🤩
Your work was merged to `dev` branch as is part of the latest extension pre-release v3.0.1
pre-releases are no installed automatically and you will need to opt-in in VS Code if you wanna test out your changes and use the latest and greatest
![image](https://github.com/pnp/vscode-viva/assets/58668583/312e0ea3-f085-4e88-9802-a93415c74fab)

Let's give it a 7 day period for pre-production use and see if anything comes up. After that I will merge this to the `main` and will create new minor release out of that 👍
If you have any doubts or questions please do not hesitate to ask
Once again thank you for your interest in making this product better 👏
Cheers mate 🍻
