### ISSUE TITLE
💡 [Feature]: Present solutions deployed per app catalog

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#215]
### 🎯 Aim of the feature

The aim of this issue is to show apps deployed to each app catalog (similar way like we now present tenant-wide extensions for tenant level app catalog)

Additionally, we could introduce the following features:
- allow to disable and enable a solution
- allow to move solutions between app catalogs (from site level to tenant level and the other way around)
- allow to remove and retract a solution
- clicking on app link should go to the solution appStore.aspx page
- allow to add a webpart to all sites

we should add an extension setting that will allow to hide this information in the UI

### 📷 Images (if possible) with expected result

![image](https://github.com/pnp/vscode-viva/assets/58668583/8748c534-6378-4a27-a79c-e5544e404100)

### 🤔 Additional remarks or comments

parent issue: #15

**Comment by Saurabh7019** [comment]
Hi @Adam-it , Can you assign this to me please?

**Comment by Adam-it** [comment]
> Hi @Adam-it , Can you assign this to me please?

Sure thing. 
This one is a bit more difficult. Please do ask questions if you have any kind of problem or doubt 👍

**Comment by Saurabh7019** [comment]
Hi @Adam-it, 
Is cli-cjs updated? I am getting an error in the latest dev branch:

![image](https://github.com/pnp/vscode-viva/assets/18114579/28d16469-e072-42f8-841a-fbd47c3640eb)

The account signin is not working.

![image](https://github.com/pnp/vscode-viva/assets/18114579/b7305614-f2cb-4c47-b90f-827b843d8614)

**Comment by Adam-it** [comment]
> Hi @Adam-it, Is cli-cjs updated? I am getting an error in the latest dev branch:
> 
> ![image](https://private-user-images.githubusercontent.com/18114579/347726260-28d16469-e072-42f8-841a-fbd47c3640eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODQ4OTUsIm5iZiI6MTcyMDY4NDU5NSwicGF0aCI6Ii8xODExNDU3OS8zNDc3MjYyNjAtMjhkMTY0NjktZTA3Mi00MmY4LTg0MWEtZmJkNDdjMzY0MGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA3NTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Yzg0MTE1YzdhODVmZmQxOTU1OTliMTAzMDA0Yzc5ZmU3ZWU2YmVkZTNmNjI3ZDljNzQyYjZkN2ZhNzcyZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1EukUOComghvCDs0Yhk74IJn-Xh-6AWiamZaaN5uoio)
> 
> The account signin is not working.
> 
> ![image](https://private-user-images.githubusercontent.com/18114579/347729300-b7305614-f2cb-4c47-b90f-827b843d8614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODQ4OTUsIm5iZiI6MTcyMDY4NDU5NSwicGF0aCI6Ii8xODExNDU3OS8zNDc3MjkzMDAtYjczMDU2MTQtZjJjYi00YzQ3LWI5MGYtODI3Yjg0M2Q4NjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA3NTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMTlmMTdkYTE1Zjk0MDI2ZWM2MmE3MjcwNGJlNjM2NjVmNTUwYjBkZmE1YzU2ODFkMjMwNmI2MTNlNDZhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x-LV6qyBsveLbp9k279eyGdkinnQQIMMkXR_Z9OIzwk)

how did you obtain cli-cjs version? 
I am asking as currently it is very hacky and tricky and there is no good way around it. and running just npm install wont solve this.
What you need to do i to manually replace CLI for M365 in node modules with your local version of CLI in cjs
you may do it by follwoing those steps:

- Clone the cjs version of CLI for Microsoft 365 from the following Github repo/branch [cli-cjs](https://github.com/Adam-it/cli-microsoft365/tree/cli-cjs) next to vscode-viva repo
- In the cloned CLI for Microsoft 365 repository, run: npm install, npm run clean, npm run build to generate the CLI for Microsoft 365 output. Make sure the cloned CLI for Microsoft 365 repository is in the same workspace as the SharePoint Framework Toolkit repository. So for example you should have the following structure:

```
root:
  - cli-microsoft365
  - vscode-viva  
```

- from the cloned for of SharePoint Framework Toolkit repository run the following script [cli-for-microsoft365-copy-local-version](https://github.com/pnp/vscode-viva/blob/main/scripts/cli-for-microsoft365-copy-local-version.ps1) passing the workspacePath the full path to the root folder of the workspace. This script will copy the output of the CLI for Microsoft 365 to the SharePoint Framework Toolkit extension node modules folder.

**Comment by Saurabh7019** [comment]
I was trying exactly as you mentioned. I tried again with a fresh clone, and now I am getting another issue:

![image](https://github.com/pnp/vscode-viva/assets/18114579/21803769-62df-490b-8706-99d117612686)

If it works fine for you, I must be doing something wrong. I will try again later today.

**Comment by Adam-it** [comment]
> I was trying exactly as you mentioned. I tried again with a fresh clone, and now I am getting another issue:
> 
> ![image](https://private-user-images.githubusercontent.com/18114579/347752203-21803769-62df-490b-8706-99d117612686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODkxMTUsIm5iZiI6MTcyMDY4ODgxNSwicGF0aCI6Ii8xODExNDU3OS8zNDc3NTIyMDMtMjE4MDM3NjktNjJkZi00OTBiLTg3MDYtOTlkMTE3NjEyNjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA5MDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMzgyYWY3MzkyZDM3MzcyYzI1MTBkZTJkMjViMzNjZjI2NzYzZTRmYWRhY2NlNmU4NWE0ZWE5ZDU5N2U4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xOVx1uq4sMR820tWFTjqBt-VTkllzkoBYzDq8Q1aU2k)
> 
> If it works fine for you, I must be doing something wrong. I will try again later today.

this error says that you are using esm version of js which is not supported in VS Code extensions. 
This would seem like you still have CLI in esm no in cjs from my branch 🤔. 
Are you trying to add some CLI command which is not already used? maybe there is some bug in cli-cjs branch 🤔. do you wanna share your branch with your changes done so far and some details? I could give it a check over the weekend

**Comment by Saurabh7019** [comment]
It works after cleanup. Thanks for looking into it. I will work on this issue soon; have a great summer. :)

**Comment by Adam-it** [comment]
Hi @Saurabh7019 
Hows the work coming up with this issue?
Do you need any additional help from my side? 
This year the SPFx Toolkit repo will participate in hacktoberfest and this issue will count so if you are also planning to join this event please do remember to rise a PR during October (no sooner no later 😉)

**Comment by Saurabh7019** [comment]
Hi @Adam-it ,

Thanks for checking in. Most of the features are done, except for the 'Move apps between app catalogs' part. Also, to improve the extension load times, I made changes in ActionTreeDataProvider so that apps and extensions are loaded only when the user expands the relevant tree view node (I can undo this if needed during review). Right now, it looks like this:                              
                 
![image](https://github.com/user-attachments/assets/ef8de5ee-5300-4a39-8067-35063075f467)

I did most of the work during the summer vacation, but I am struggling to find time to wrap it up now. In hindsight, we should have broken this into multiple issues; it would have made things easier. 

I will try to work on "Move apps" feature early next week and raise a PR.

**Comment by Adam-it** [comment]
> Hi @Adam-it ,
> 
> Thanks for checking in. Most of the features are done, except for the 'Move apps between app catalogs' part. Also, to improve the extension load times, I made changes in ActionTreeDataProvider so that apps and extensions are loaded only when the user expands the relevant tree view node (I can undo this if needed during review). Right now, it looks like this:
> 
> I did most of the work during the summer vacation, but I am struggling to find time to wrap it up now. In hindsight, we should have broken this into multiple issues; it would have made things easier.
> 
> I will try to work on "Move apps" feature early next week and raise a PR.

wow looks really awesome 🤩 You Rock 🚀😍.
Some feed/question from my side:

- what if for the `move app` feature we create a follow issue and take it later on when we have more time. I guess as first go we do not have to introduce everything at once 💪
- what does the `remove` do? is it moving to recycle bin or permanent remove or there is a follow up question what should be the action?
- what does the `deploy` do? does it install it on a selected SharePoint site? Because the app is already deployed to an app catalog right
- I was also wondering if it would be better to add those 'actions' next to the app name not under it like this 
![image](https://github.com/user-attachments/assets/4ef837ee-2061-4e3d-a1a6-72d8e4ca9046)
it's also possible to add `...` with menu to more options like this 
![image](https://github.com/user-attachments/assets/50ad61e5-526c-439d-b765-159c72d51185)
we already use those actions next to the account to show the sign-out button here
https://github.com/pnp/vscode-viva/blob/fc90031f0900c459b1d1f671e2c279f74d9d76a1/package.json#L411-L417


BTW awesome to see you are also using the CLI VS Code extension 😍

**Comment by Saurabh7019** [comment]
> * what if for the `move app` feature we create a follow issue and take it later on when we have more time. I guess as first go we do not have to introduce everything at once 💪
_Sounds good!_

> * what does the `remove` do? is it moving to recycle bin or permanent remove or there is a follow up question what should be the action?
_`remove` is inverse of the `add`. It moves the app to recycle bin. Once removed from the app catalog, the solution can't be deployed._

> * what does the `deploy` do? does it install it on a selected SharePoint site? Because the app is already deployed to an app catalog right
_Deployment of the solution makes it available to install in sites. It does not automatically install it on the selected site._

> * I was also wondering if it would be better to add those 'actions' next to the app name not under it like this.
_This design looks so much better. I will make this change._

> * Additionally, we have Enable and Disable actions:
_`Enable`: Enabling an app will allow end users to see it as an option to add to their SharePoint sites.
`Disable`: Disabling the app will hide it from end users, preventing them from adding it to sites._

**Comment by Adam-it** [comment]
@Saurabh7019 Awesome work 👏👏👏. You Rock 🤩
I just merged the PR and will try to create a pre-release ASAP 👍
@Saurabh7019 would you be so kind and create a follow up issue to this one? 
I think we could think of more manage features like: 
- promoting to tenant-level from site-level
- install to a specified sitecollection (we could present an additional input to specify the site URL)
- uninstall from a specified sitecollection (we could present an additional input to specify the site URL)
- upgrade the app at the specified sitecollection

what do you think 😍 Sounds really awesome right 👍

**Comment by Adam-it** [comment]
> Absolutely, I'd be happy to create a follow up issue.

Awesome. Thanks a ton 👏👏
 
> I noticed that you have not included the 'allow to move solutions between app catalogs' feature. I think that's a good idea; I have never encountered such a use case. If anything, it should be 'Allow to **copy** solutions between app catalogs.'

Yes I forgot about that. We could have one single issue to group all ideas what could be included there (like an epic) and then create 'sub issues' with a issue describing a single action we could add. Similar approach we take in CLI for M365 with adding new command areas.

> I was also thinking about the extension settings to hide apps/extensions. Since we now only load them when the nodes are expanded to ensure that the additional API calls don't affect the extension load time, do we really need additional extension settings to hide/show them?

Good call. This setting doesn't make sense now. We could either remove this setting totally or we could try to rebuild it to a setting that will allow to either load apps from appcatalogs or don't and show only the app catalog list. What do you think? This could be a separate issue as well 😉. I will try to create one for that. Good team work 👍

> For now, I will create an issue to track the four ideas you suggested. We can always add more when you have had a chance to review them..

Feel free to point out more ideas if you have any. I was thinking also of a action that would show the app details in the SPFx Toolkit extension like to what hosts is it applicable (like Teams Tab or Personal App etc).

**Comment by Saurabh7019** [comment]
> I was thinking also of a action that would show the app details in the SPFx Toolkit extension like to what hosts is it applicable (like Teams Tab or Personal App etc).

Are you referring to presenting the `supportedHosts` property from the web part manifest? If so, I am curious how that would work for an app that contains multiple web parts?

**Comment by Adam-it** [comment]
> Are you referring to presenting the `supportedHosts` property from the web part manifest? If so, I am curious how that would work for an app that contains multiple web parts?

that's why we have prototype stage for every feature 😉 Wanna brainstorm on this?

**Comment by Saurabh7019** [comment]
> Wanna brainstorm on this?

Absolutely! :)
