### ISSUE TITLE
💡 [Feature]: Sample gallery could have a filter by extension type when extension is selected

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#219]
### 🎯 Aim of the feature

We could extend the sample gallery with an additional filter option that should be visible only when the extension component type is selected. The new option should allow to filter by SPFx extension type.

### 📷 Images (if possible) with expected result

![image](https://github.com/pnp/vscode-viva/assets/58668583/6c09e95d-1ab1-4e50-b928-6723082ee8e8)

**Comment by nicodecleyre** [comment]
Great addition @Adam-it 🙌

Can I work on it please? 😄

**Comment by Adam-it** [comment]
Yes please 🤩.
Please be sure to recheck the [contributing notes](https://github.com/pnp/vscode-viva/blob/main/contributing.md) before you start.
Please do not hesitate to ask any kind of question or share any kind of problem when implementing this feature, I am here to help 👍

Happy coding!

**Comment by Adam-it** [comment]
The related PR is closed and this is already part of a new pre-release. 
Lets give it a bit of time and shortly after we will release a new minor with this included 👍.
Thank you for your contribution. You Rock 🤩👏
