### ISSUE TITLE
🐞 Bug report: the name/description/tag filter does not work well and has lags

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#220]
### ⭐ Priority

(Low)☹️ Something is a little off

### 📝 Describe the bug

when writing in the search field it seems to have some 'lag' and some letters are avoided

### 👣 Steps To Reproduce

1. open sample gallery
2. start writing really fast in the `search` field

### 📜 Expected behavior

should always contain the whole written word

### 📷 Screenshots

![image](https://github.com/pnp/vscode-viva/assets/58668583/af8285b7-41ab-48ba-9400-51d33e9be513)

**Comment by Saurabh7019** [comment]
Hi @Adam-it , Can I work on it?

**Comment by Adam-it** [comment]
> Hi @Adam-it , Can I work on it?

Yes 😍👍
You Rock 🤩👏👏👏

**Comment by Adam-it** [comment]
PR merged ✅ 
@Saurabh7019 awesome work 👏👏 
A pre-release with this fix should be out shortly and as soon as we process more PR's we will create new minor release and this fix will be included as well.
You Rock 🤩
