### ISSUE TITLE
💡 [Feature]: Refactor scaffolding form to smaller components

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#221]
### 🎯 Aim of the feature

The aim is to refactor the scaffolding form to a smaller and more reusable components. 
We could use the gallery view as example

### 📷 Images (if possible) with expected result

![image](https://github.com/pnp/vscode-viva/assets/58668583/8191acec-1dd5-43ed-9248-43cf93009311)

**Comment by Saurabh7019** [comment]
Hi @Adam-it , May I attempt this?

**Comment by Adam-it** [comment]
> Hi @Adam-it , May I attempt this?

Totally!!!
All yours 👍. You Rock 🤩
Let me know if you will need any help along the way, currently the build process is a build hacky

**Comment by Saurabh7019** [comment]
I think I accidentally unassigned myself. I would still like to work on it and would appreciate it if you could reassign it to me.

**Comment by Saurabh7019** [comment]
Also, could you please let me know if there is anything special that needs to be done to be able to debug the extension? My code changes are reflecting but the breakpoints are not currently binding when I hit F5.

**Comment by Saurabh7019** [comment]
Trying exactly that. Debugging the TypeScript classes are working correctly, but breakpoints in React components are unbound. Anyway, it's not that urgent for my current task, I will look into it later.

**Comment by Adam-it** [comment]
The PR was merged.
This refactor will be part of the next minor release.
@Saurabh7019 thank you for your awesome work 👏👏👏. You Rock 🤩
As soon as this is merged to main you will also show up as a contributor to the repo 👍

**Comment by Saurabh7019** [comment]
> As soon as this is merged to main you will also show up as a contributor to the repo

Thank you so much. :) 
It's truly an honor. I'm looking forward to continuing to contribute to this amazing project.
