### ISSUE TITLE
💡 [Feature]: Correct the VS Code extension name in assets images

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#225]
### 🎯 Aim of the feature

Go over the assets images and sort out the naming so that it will be SharePoint Framework Toolkit in every image 

### 📷 Images (if possible) with expected result

example image taken from the readme with this problem

![image](https://github.com/pnp/vscode-viva/assets/58668583/ec46ff08-000d-42f5-af13-b1bced7a18dc)

**Comment by tmaestrini** [comment]
I'm interested in being assigned… That's a good starting point! :)

**Comment by Adam-it** [comment]
@tmaestrini so to maybe give you some more context or info that might be helpful to resolve this issue:
- all of the images may be found in `assets/images` location
- if you will need to recreate the images from scratch please do be aware that:
    - the primary color of SPFx Toolkit is `#2A777C` which should be used in text areas and arrows
    - we should use default Light + VS Code theme when creating images 
    
![image](https://github.com/pnp/vscode-viva/assets/58668583/5647f578-016f-4b27-acdf-4ca5a598e660)

**Comment by Adam-it** [comment]
@tmaestrini it has been a while. Do you want to continue working on this or would you like to open it up for the community?

**Comment by tmaestrini** [comment]
Hey @Adam-it, I definitely would love to work on it! 💪 I haven't had time yet, that wasn't intentional!

**Comment by Adam-it** [comment]
> Hey @Adam-it, I definitely would love to work on it! 💪 I haven't had time yet, that wasn't intentional! Sorry! 🙏

No problem. Keeping it for you then 👍

**Comment by Adam-it** [comment]
@tmaestrini I corrected the images in the readme along a bigger change I merged to dev just now. This should be release (I hope) today. 
Thank you once again for taking an interest in this repository 👍.  If you still want to help out there are plenty of other issues for grasps 😉
