### ISSUE TITLE
🐞 Bug report: Unable to Signin from Extension

### ISSUE THREAD

**Issue by urwahumer** [pnp/vscode-viva#244]
### ⭐ Priority

(Low)☹️ Something is a little off

### 📝 Describe the bug

I'm encountering an issue signing into M365 using the SPFX toolkit extension. This problem is preventing me from fully leveraging the benefits of the extension. When I click on it, it prompts me to enter the code displayed on my device. However, I don't receive any code. My account has MFA enabled, and even after entering the code from the authenticator app into the Microsoft dialog, I still receive an error.

### 👣 Steps To Reproduce

I'm encountering an issue signing into M365 using the SPFX toolkit extension. This problem is preventing me from fully leveraging the benefits of the extension. When I click on it, it prompts me to enter the code displayed on my device. However, I don't receive any code. My account has MFA enabled, and even after entering the code from the authenticator app into the Microsoft dialog, I still receive an error.

### 📜 Expected behavior

Might be Im doing a or looking for wrong way is there any video tuts which can I follow .

### ❓SharePoint Framework Toolkit version

v3.2.1

### ❓Node.js version

v18.20.2.

**Comment by Adam-it** [comment]
Thank @urwahumer for reporting an issue. You Rock
I will get on it ASAP

**Comment by Adam-it** [comment]
@urwahumer this is how the login 'should' work:
- click on the login button in the SPFx Toolkit account panel (alternatively you may use the `>SharePoint Framework Toolkit: Sign in to M365` VS Code command)
- it will show you a popup where you may allow to open up the browser for you. If you wont allow it you may do it manually afterwards as well.
- after that you should see  the prompt that explains the login process. It uses Device Code authentication which is default for authentication method. As you may see in the notify you get the device code which BTW is automatically copied for you to the clipboard so you do not need to do that. It should open up your default browser in the MS Device Code login page. If it did not please use the link 'Open Browser to authenticate' which is present in this notify
![image](https://github.com/pnp/vscode-viva/assets/58668583/fb037593-38d7-4f13-9c1a-c3aba0ab1c2a)
- in the open browser you need to paste the device code. After that login to you tenant (best as admin) and approve the PnP Management Shell app to be added with the required scopes
- after that you may close your browser and it should, after a few seconds, show you the management features.

please check the recording below for additional help 👇

https://github.com/pnp/vscode-viva/assets/58668583/76c57367-9414-4d6e-b29b-6ed0c887fa15

Based on this issue I will create a dedicated wiki page to have this info saved for future. 

@urwahumer let me know if in your case it is acting differently and let me know how. So we could try to point out the problem. 
Also if something is not working please do check the logs by going to the output window and showing the output of the SPFx Toolkit 
![image](https://github.com/pnp/vscode-viva/assets/58668583/57e01651-5f77-4c3d-b3d8-8efb8dfebf2b)

**Comment by Adam-it** [comment]
I extended wiki guidance with this process
https://github.com/pnp/vscode-viva/wiki/5.3-Login-to-your-tenant-&-retrieve-environment-details#login-process

**Comment by urwahumer** [comment]
Thank you for your response.
I followed your instructions ,now its working fine.
Thanks Alot.

**Comment by Adam-it** [comment]
> Thank you for your response.
> I followed your instructions ,now its working fine.


Awesome to hear that 👍.
Closing this as resolved than. 
Take care and happy coding 👍

**Comment by urwahumer** [comment]
Great!
