### ISSUE TITLE
💡 [Feature]: make walkthrough button more visible in welcome experience

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#261]
### 🎯 Aim of the feature

The aim is to make the walkthrough button more visible in the welcome view.
Currently, it is presented as a simple link at the bottom

![image](https://github.com/pnp/vscode-viva/assets/58668583/09d5b7a8-0b06-4c09-b539-cb1bcfcbbf1a)

The aim is to refactor it to a separate button instead of a link that could be under the 'Install dependencies' button. It could have a header above it like "Learn more about SharePoint Framework and this toolkit" 

### 📷 Images (if possible) with expected result

![image](https://github.com/pnp/vscode-viva/assets/58668583/983969cf-a7be-4f6e-ba5f-a39b31d41df3)

### 🤔 Additional remarks or comments

in VS Code the welcome experience is fully created based on a string 😱 added directly in package.json 
![image](https://github.com/pnp/vscode-viva/assets/58668583/add99ce2-9bcd-4b66-8b39-14e33186ad49)

currently there is no way to improve/extract it and this is how it is suppose to be done according to the docs.

https://code.visualstudio.com/api/ux-guidelines/views#welcome-views

this is the part that needs to be extended

**Comment by DevPio** [comment]
I would like to work on this problem

**Comment by Adam-it** [comment]
> I would like to work on this problem
> 
> 

Sure thing👍
You Rock 🤩👏

**Comment by Adam-it** [comment]
The related PR got merged and will be part of next pre-release shortly
After that it will be merged to `main` and part of next minor release in the following days.
Thank you for your awesome work 👏👏👏
You Rock 🤩
