### ISSUE TITLE
💡 [Feature]: Improve create new project walkthrough step

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#267]
### 🎯 Aim of the feature

To the create new project step in the walkthrough let's add more guidance which will explain what type of components are possible to be created and what are their benefits

![image](https://github.com/pnp/vscode-viva/assets/58668583/8be19538-e119-4015-b280-9dbbcd69abf6)

### 🤔 Additional remarks or comments

we should update this 

![image](https://github.com/pnp/vscode-viva/assets/58668583/2710a97f-ea96-43bc-87b0-74416058a25f)

**Comment by Saurabh7019** [comment]
@Adam-it, Can you assign it to me please?

**Comment by Adam-it** [comment]
> @Adam-it, Can you assign it to me please?

All yours 👍

**Comment by Adam-it** [comment]
Merged ✅ 
a new pre-release with this change will come our shortly 👍. After sometime we will merge this to `main` branch to be part of next minor release 💪
You Rock 🤩

**Comment by Adam-it** [comment]
Pre-release will be out shortly 👏
This will be part of next minor release 👍
Thank you once again for your awesome contribution 😍
You Rock 🤩
