### ISSUE TITLE
💡 [Feature]: Improve guidance in the scaffolding form

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#268]
### 🎯 Aim of the feature

The aim of this issue it to add more guidance to the scaffolding form. Currently we allow to pick any type of component and it's sub type but we don't explain what is possible and why would this be created. 

![image](https://github.com/pnp/vscode-viva/assets/58668583/00c0500a-9ebd-46cf-9bb6-fff1ce0ce392)

we should improve that. Lets add more guidance for each component type and ace or extension type. It maybe be a simple sentence which will explain what is possible and why would someone create this kind of component type or sub type

### 🤔 Additional remarks or comments

we should update this part 

![image](https://github.com/pnp/vscode-viva/assets/58668583/cf9175c7-c93a-47c9-aa45-100f401a4600)

**Comment by DevPio** [comment]
I would like to work on this problem

**Comment by Saurabh7019** [comment]
I am wondering if adding too much text directly on the form could clutter the user interface, especially for those who are already familiar with the different component types and their subtypes. 

Could showing it on tooltip work?

![image](https://github.com/pnp/vscode-viva/assets/18114579/c11f4994-6bf2-45ad-a78e-0eb29adf43ce)

**Comment by Adam-it** [comment]
> I would like to work on this problem

oh sorry I didn't notice your comment 🙏 all yours

**Comment by Adam-it** [comment]
> I am wondering if adding too much text directly on the form could clutter the user interface, especially for those who are already familiar with the different component types and their subtypes.
> 
> Could showing it on tooltip work?

this is a very good idea!. 
@DevPio what do you think?

**Comment by DevPio** [comment]
Great idea! I'll follow it.

**Comment by Adam-it** [comment]
Merged 👏.
This will be live shortly 👍
