### ISSUE TITLE
💡 [Feature]: Refactor action naming

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#287]
### 🎯 Aim of the feature

Due to new actions that will come, like the upgrade app action, which may be confusing with the current upgrade project action we should rename the current Actions to make the naming more descriptive.
I propose the following
![image](https://github.com/user-attachments/assets/4373eb3d-b17e-4da5-b236-5c75c99fa2cd)

The naming on the UI may be corrected in https://github.com/pnp/vscode-viva/blob/main/src/panels/CommandPanel.ts in `actionsTreeView` method

We should also align/correct the name of the equivalent VS Code commands for each of those actions and those we may find in the package.json

**Comment by maximkol** [comment]
@Adam-it can you please assign it to me?

**Comment by Adam-it** [comment]
> @Adam-it can you please assign it to me?

All yours 👍.
You Rock 🤩

**Comment by Adam-it** [comment]
@maximkol how's it going? 
I noticed your PR still requires some updates. 
Let me know if you need any help 👍? Don't be shy, we are all here to help you succeed and learn and help us 😊. 
Also if anything changed and you are unable to commit more time on this issue also please be honest and lets us know so we may unblock this and maybe someone else would like to take it over 👍. No problem if anything changed, totally understandable 😊. 

Have an awesome day!
Cheers

**Comment by Adam-it** [comment]
@maximkol I finished of this change if a separate commit 
https://github.com/pnp/vscode-viva/commit/c03bd3f91f47e29dea81305d136d661b5a4c70df

Thank you for taking an interest in this repository 👍
You Rock 🤩
