### ISSUE TITLE
🐞 Bug report: SharePoint Framework Toolkit does not show on the activity bar

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/vscode-viva#303]
### ⭐ Priority

(Urgent)⚠️😱 I can't use the extension

### 📝 Describe the bug

SharePoint Framework Toolkit does not show on the activity bar so I can't click on it.

### 👣 Steps To Reproduce

Just install the extension.

### 📜 Expected behavior

Show on the activity bar

### 📷 Screenshots

![image](https://github.com/user-attachments/assets/1be627e9-9994-42db-9c5e-acda120b18da)

### ❓SharePoint Framework Toolkit version

4

### ❓Node.js version

v18.18.2

**Comment by Adam-it** [comment]
hi @Ofer-Gal, 
Thank you for using SPFx Toolkit and sorry to hear you are experiencing problems at the very start.
May I kindly ask you for additional info:
- when you right-click  on the activity bar do you see it on the list? maybe it is unselected, therefore hidden
![image](https://github.com/user-attachments/assets/5438b8cd-3b97-4079-b177-79ec99066bec)

- if you open the output and show logs for `Extension Host` do you see any rows for `m365pnp.viva-connections-toolkit`?
![image](https://github.com/user-attachments/assets/a7c7853d-ddfc-4713-aa93-3edd44e45d18)

**Comment by Ofer-Gal** [comment]
Thanks.
No to the first 
There is an error for the second:
2024-09-20 09:43:20.951 [info] ExtensionService#_doActivateExtension m365pnp.viva-connections-toolkit, startup: false, activationEvent: 'onStartupFinished'
2024-09-20 09:43:23.314 [error] SyntaxError: Expected double-quoted property name in JSON at position 380 (line 12 column 57)
    at JSON.parse (<anonymous>)
    at Function.init (c:\Users\ofgal\.vscode\extensions\m365pnp.viva-connections-toolkit-4.0.0\dist\extension.js:2:429040)
2024-09-20 09:43:47.584 [warning] vscode.json-language-features - Code actions of kind 'source.fixAll.eslint' requested but returned code action is of kind 'source.sort.json'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.

What should I do?

**Comment by Ofer-Gal** [comment]
Uninstalling and installing did not work.
Copied all of \.vscode-insiders\extensions\m365pnp.viva-connections-toolkit-4.0.0 to 
\.vscode\extensions\m365pnp.viva-connections-toolkit-4.0.0 and now it shows correctly. 
Thank you for the hint.

**Comment by Adam-it** [comment]
> Uninstalling and installing did not work.
> Copied all of \.vscode-insiders\extensions\m365pnp.viva-connections-toolkit-4.0.0 to 
> \.vscode\extensions\m365pnp.viva-connections-toolkit-4.0.0 and now it shows correctly. 
> Thank you for the hint.

Wow, seems like you did an awesome job resolving it on your own 🤩. You Rock 🤩😍👏👏👏

I am very sorry I did not provide any help, I did saw your message and I was going to investigate but I may only work on open source projects only over the nights as weekends during the day are my family time which is most important 🙂 and I only do updates over the phone

**Comment by Ofer-Gal** [comment]
You rock more 😉💕
