### ISSUE TITLE
🐞 Bug report: Tenant-wide Extensions Not Loading by Default

### ISSUE THREAD

**Issue by Saurabh7019** [pnp/vscode-viva#317]
### ⭐ Priority

(Low)☹️ Something is a little off

### 📝 Describe the bug

The tenant-wide extensions are not loading as expected when the setting `showTenantWideExtensions` is using its default value (true). 

### 👣 Steps To Reproduce

1. Use the extension with the default settings (do not manually update `showTenantWideExtensions` in settings).
2. Observe that tenant-wide extensions are not loaded.

### 📜 Expected behavior

Tenant-wide extensions should load by default when the `showTenantWideExtensions` setting is true.

### 📷 Screenshots

![image](https://github.com/user-attachments/assets/bc1712f4-f462-4c3c-9af4-67b897e64aba)

### ❓SharePoint Framework Toolkit version

4.1.1

### ❓Node.js version

v20.9.0

**Comment by Adam-it** [comment]
@Saurabh7019 and if you click on refresh view button in the upper right corner of this panel? Or refresh the account view?

**Comment by Saurabh7019** [comment]
Refreshing isn't resolving the issue. Both `showTenantWideExtensions` and `showServiceIncidentList` settings are not working. It requires a code fix as you can see below:

![image](https://github.com/user-attachments/assets/ef34a554-c8de-40c5-a823-a778fe356d2c)

**Comment by Adam-it** [comment]
thanks for the heads up and investigation. Just had a quick check and in my case seems to be working perfectly fine 🤔
![image](https://github.com/user-attachments/assets/9c65f508-3989-4224-a409-135ca5715502)

never the less I think I will double check the code and try to check why you have string there instead of boolean. It seems somewhere we are loosing types 🤷‍♂️

**Comment by Adam-it** [comment]
@Saurabh7019 sorry yesterday I doze off on the laptop and forgot to perform a pre-release with this fix 🙏
I did one just now https://github.com/pnp/vscode-viva/actions/runs/11230480092/job/31217916362
should be present on VS Code marketplace within 5-10 min
