### ISSUE TITLE
🐞 Bug report: M365 Signin / App Registration in WSL

### ISSUE THREAD

**Issue by DonKirkham** [pnp/vscode-viva#318]
### ⭐ Priority

(Low)☹️ Something is a little off

### 📝 Describe the bug

My primary development environment is Windows Subsystem for Linux (WSL), which is where the issues below happen. I have installed and used the SPFx Toolkit in my Windows environment with no issues.

In WSL, when I open a project and go to the SPFx Toolkit extension, I do not see the Sign in to Microsoft 365 message. Instead, I get the following message in the Account and Actions sections:  There is no data provider registered that can provide view data.

![image](https://github.com/user-attachments/assets/77ae3f86-b7ce-42ea-9869-edf78f0291ee)

I can manually go to the command: SharePoint Framework Toolkit: Sign in to Microsoft 365
The automatic registration did not work, so I manually created an App Registration following the documentation.  When I use the Manual option, I provide the client ID and tenant ID, but get the following error

![image](https://github.com/user-attachments/assets/8aef882f-fff0-45b8-b5b9-09e7efb04eef)

I am not sure where the logs are for the toolkit, but will provide that information once I find the logs.

### 👣 Steps To Reproduce

Open an SPFx project in VS Code. 
Click the PnP SPFx extension button in the Activity Bar

### 📜 Expected behavior

I expect the same behavior as in Windows and the videos I have watched demoing how to connect to Microsoft 365 from the SPFx Toolkit.

### 📷 Screenshots

Provided above

### ❓SharePoint Framework Toolkit version

v4.1.0

### ❓Node.js version

v18.18.2

### 🤔 Additional context

I went back to my Windows environment, and everything there works as it should.
I have uninstalled and re-installed the SPFx Toolkit extension in my WSL environment multiple times
I have tried the Pre-relase version. Same behavior as reported above.
I tried to use to the manual app registration I create and to the new App registration I created for the Microsoft 365 CLI. Same results as reported above.

Thanks for your help!

**Comment by Adam-it** [comment]
Thanks for reporting the issue. I will get back to you with some tips and questions ASAP

**Comment by Adam-it** [comment]
@DonKirkham I tried to reproduce this error without any luck. 
![image](https://github.com/user-attachments/assets/8d12f4ac-6e5e-498f-856f-95b31072cf08)

I installed a clean WSL using ubuntu distro to have a clean state and installed SPFx Toolkit as my single extension. After that I managed to sign in without issue as you may see on the screenshot. 

May I kindly ask you for the following info to help me progress or investigate the case:
- what distro you are using?
- besides SPFx Toolkit VS Code extension do you also have CLI for Microsoft 365 installed on WSL? 
- to get more logs regarding SPFx Toolkit please open the `OUTPUT` panel and select SharePoint Framework Toolkit nas output source. There you will see every log and error SPFx Toolkit is throwing. May I kindly ask you to give this view a check and copy over any error you see. Please be aware you will see raw commands output there
![image](https://github.com/user-attachments/assets/d2eb833a-817a-4ef3-b8bd-bf34e8e21725)
- when you try running any other SPFx Toolkit functionality that does not require sign in do you also experience some issues?

**Comment by Adam-it** [comment]
@DonKirkham did you have a chance to review my previous comment 👆.

**Comment by DonKirkham** [comment]
I'm so sorry, I did not see your reply last week. I will look into your request and get back to you ASAP.

**Comment by DonKirkham** [comment]
I am running Ubuntu-22.04
I also have CLI for Microsoft 365, v 9.1.0, installed in WSL (and have used it to log into my M365 tenant)
SharePoint Framework does not show up as an option in the Output panel.

All of the commands in the Task section are working. The Actions section gives the same error as Account "There is no data provider registered that can provide view data."

I wiped out vscode in WSL and all extensions, then reinstalled vscode and only the SPFx toolkit extension. Same result

It's been a while since I installed a clean build of WSL. I am speaking at CollabDays NE this week, so maybe I'll re-install WSL next week.

**Comment by DonKirkham** [comment]
OK, I just started messing around and I was able to get signed in via the SharePoint Framework Toolkit: Sign in to Microsoft 365 from the command palette. It worked and now everything seems to be working. Weird!

**Comment by DonKirkham** [comment]
And now I can see the SharePoint Framework Toolkit option in the Output window.

[2024-10-14T21:46:46.551Z] [INFO]
> Created Entra App Registration: {"appId":"96a47c15-82e2-45f1-a891-b86d0e92816c","tenantId":"zzz-9bb5-45fb-8537-cca08fbaf370"}
[2024-10-14T21:46:46.551Z] [INFO]
> SPFx Toolkit App Registration created successfully
[2024-10-14T21:47:01.377Z] [INFO]
> status: "Logged out"
[2024-10-14T21:47:05.469Z] [INFO]
> Device code: A6UNTAF4K
[2024-10-14T21:47:32.022Z] [INFO]
> Logged in to Microsoft 365
[2024-10-14T21:47:32.023Z] [INFO]
> status: {
  "connectedAs": "dev@zzz.onmicrosoft.com",
  "authType": "DeviceCode",
  "appId": "96a47c15-82e2-45f1-a891-b86d0e92816c",
  "appTenant": "zzz-9bb5-45fb-8537-cca08fbaf370",
  "cloudType": "Public"
}
[2024-10-14T21:47:32.027Z] [INFO]
> Running CLI command: spo tenant appcatalogurl get
"https://zzz.sharepoint.com/sites/appcatalog"
[2024-10-14T21:47:33.647Z] [INFO]

**Comment by Adam-it** [comment]
> OK, I just started messing around and I was able to get signed in via the SharePoint Framework Toolkit: Sign in to Microsoft 365 from the command palette. I used the Create a new App option. It worked and now everything seems to be working.
> 
> Weird!

yes seems strange indeed. But it's good to hear you managed to get unblocked and we may always reopen this ticket and recheck you issue if it will reproduce again in the future 👍.
Thank you for your response and update on this issue. 
Have an awesome day 🤩
