### ISSUE TITLE
💡 [Feature]: Allow to upgrade an app on a specified site collection using a action in the app catalog app list view

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#351]
### 🎯 Aim of the feature

Currently we have a few actions available for each app in the app catalog list. 
The idea/aim is to add a new action which under the hood will use CLI for Microsoft 365 command:
- Upgrade - this will upgrade an app from the specified app catalog in the site. Under the hood it should use [m365 spo app upgrade](https://pnp.github.io/cli-microsoft365/cmd/spo/app/app-upgrade). When clicking on this action we should add prompt for `siteUrl` which is needed so that we will know to which site we should upgrade the selected app

Tips how to go about it, which should be done similar like already available actions
- we should define it as a new app action like this https://github.com/pnp/vscode-viva/blob/59190115e0c676068a3f1a3698e31f3500aee3f6/src/constants/Commands.ts#L56-L62
- we should add a new option for it visible in the menu under the app like this https://github.com/pnp/vscode-viva/blob/59190115e0c676068a3f1a3698e31f3500aee3f6/src/panels/CommandPanel.ts#L210-L216
- we should handle this new action like this https://github.com/pnp/vscode-viva/blob/59190115e0c676068a3f1a3698e31f3500aee3f6/src/services/actions/CliActions.ts#L54-L56 and add logic for the new method like this https://github.com/pnp/vscode-viva/blob/59190115e0c676068a3f1a3698e31f3500aee3f6/src/services/actions/CliActions.ts#L182
- The yes/no prompt may be done similar to this https://github.com/pnp/vscode-viva/blob/59190115e0c676068a3f1a3698e31f3500aee3f6/src/services/actions/CliActions.ts#L539C5-L545C69
- we should also update the readme 

### 📷 Images (if possible) with expected result

current state of actions for each app in the app catalog list
![image](https://github.com/user-attachments/assets/d7638d10-c52a-48b8-b36c-f50d2376e4e3)

### 🤔 Additional remarks or comments

parent issue #324

**Comment by Saurabh7019** [comment]
Can I take it?

**Comment by Adam-it** [comment]
> Can I take it?

All yours

**Comment by Adam-it** [comment]
PR merged. This will be live as a new pre-release soon.
Thank you once again for helping out in making the best SPFx tooling in the world 🚀
