### ISSUE TITLE
💡 [Feature]: Improve upgrade app action 

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#359]
### 🎯 Aim of the feature

As of now when we run the upgrade command on tenant scope app catalog we need to provide full URL to the site. like `https://tenanttocheck.sharepoint.com/sites/PnPDemo2`. But SPFx Toolkit is already aware of my tenant Url so `https://tenanttocheck.sharepoint.com/`. It would be awesome if the user could only provide `sites/PnPDemo2`. 

What we could do we could pass the tenant URL here
https://github.com/pnp/vscode-viva/blob/2ed802ee1c0d49225051c28e5cc4311c3ac00e5a/src/panels/CommandPanel.ts#L215

and then update the `upgradeAppCatalogApp` method 
https://github.com/pnp/vscode-viva/blob/2ed802ee1c0d49225051c28e5cc4311c3ac00e5a/src/services/actions/CliActions.ts#L235

to either:
- prefill the `siteUrl` input with tenant URL 
- or allow to specify only the relative path and then concat it under the hood with the tenant Url

### 🤔 Additional remarks or comments

Follow up to issue: #351
based on idea from this PR review comment: https://github.com/pnp/vscode-viva/pull/357#discussion_r1855297987

**Comment by Adam-it** [comment]
@Saurabh7019 Since this idea was based on your work may I kindly ask for your feed on this before we open it up?🙏

**Comment by Saurabh7019** [comment]
I like it! It would definitely make providing the site URL easier for **'Upgrade'** and a few other actions. 

Autocomplete could be the ideal solution if its available built-in in VS Code. If not, should we explore some workarounds for implementing something similar before proceeding with the changes you proposed?

**Comment by Adam-it** [comment]
> I like it! It would definitely make providing the site URL easier for **'Upgrade'** and a few other actions.
> 
> Autocomplete could be the ideal solution if its available built-in in VS Code. If not, should we explore some workarounds for implementing something similar before proceeding with the changes you proposed?

not sure if there is some autocomplete for VS Code prompts. How I went about it till now is just prefill the value for the user so that when presented the user may just click enter to confirm or add some more info.
Do you see any other places we could add this kind of autocomplete?

**Comment by Saurabh7019** [comment]
We could start with an input to provide partial site UR, then use it in 'spo tenant site list' filter and bind the results to a showQuickPick. Performance could be an issue though. Is it worth checking?

**Comment by Saurabh7019** [comment]
> Do you see any other places we could add this kind of autocomplete?

app install/uninstall could use also this approach.

**Comment by Adam-it** [comment]
> We could start with an input to provide partial site UR, then use it in 'spo tenant site list' filter and bind the results to a showQuickPick. Performance could be an issue though. Is it worth checking?

I also had this idea but usually there are a looooot of sites. Even my dev tenant has more than 200+ sites 🤯
So for now I would just prefill with tenant URL and let the user finish it off without any search.
We may also ask GH Copilot to search for a site by title which BTW also now has a problem due to token limit 😁

**Comment by Saurabh7019** [comment]
> So for now I would just prefill with tenant URL and let the user finish it off without any search.

Makes sense. I can make this change tonight if you assign it to me.

**Comment by Adam-it** [comment]
a new pre-release with this will be available shortly
