### ISSUE TITLE
💡Feature Idea - extensions and webpart samples view 

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-viva#6]
## 💡 Idea

I was wondering maybe since the extension already allows to create webpart, extensions ect. 

![image](https://user-images.githubusercontent.com/58668583/193161439-1cc3d632-fc5a-4318-a97b-357dc9bb42be.png)

And we do have a lot of great community samples for those maybe we should create similar sample views for webparts and extensions like we have for the adaptive cards.

.... or is this out of scope for this extension 😉?

**Comment by estruyf** [comment]
We also thought about it, but first focus would be Viva Connections, next we can see what we'll add more or how to bring in other experiences.

**Comment by Adam-it** [comment]
Great, if you will be looking for additional pair of hands to share work I would love to help out and learn 😉.
If you want to start discussing the features to create some detail plan and point out what would be the first step to make it happen I am also all in 🤩

**Comment by Adam-it** [comment]
- [ ] recheck why the script trimmed out one ACE sample 🤔 https://github.com/pnp/vscode-viva/pull/38/files#diff-87f6a5cbd961f31660a3c779526f5244ec05edf11e408620261b8b771a8a65a9 -> maybe open a separate issue for it
